### ISSUE TITLE
error

### ISSUE THREAD

**Issue by semen7907** [MyUCP/MyUCP#2]
Parse error: syntax error, unexpected '[', expecting ')' in Z:\home\test1.ru\www\new\engine\protected\Debug\DebugErrorHandler.php on line 7

Постоянно выдает данную ошибку, не зависимо от настроек  главного конфига.
 Подскажи в чем может быть проблема,  и как ее исправить? 
зы запускаю на локалке Denwer

**Comment by maksa988** [comment]
Версия php не подходит.
Нужно минимум 5.4 (http://myucp.ru/docs#Требования к серверу)

Рекомендую использовать OpenServer
